namespace BIliliveRecorder.Huya;

public enum EWebSocketCommandType
{
    EWSCmd_NULL = 0,
    EWSCmd_RegisterReq = 1,
    EWSCmd_RegisterRsp = 2,
    EWSCmd_WupReq = 3,
    EWSCmd_WupRsp = 4,
    EWSCmdC2S_HeartBeat = 5,
    EWSCmdS2C_HeartBeatAck = 6,
    EWSCmdS2C_MsgPushReq = 7,
    EWSCmdC2S_DeregisterReq = 8,
    EWSCmdS2C_DeRegisterRsp = 9,
    EWSCmdC2S_VerifyCookieReq = 10,
    EWSCmdS2C_VerifyCookieRsp = 11,
    EWSCmdC2S_VerifyHuyaTokenReq = 12,
    EWSCmdS2C_VerifyHuyaTokenRsp = 13,
    EWSCmdC2S_UNVerifyReq = 14,
    EWSCmdS2C_UNVerifyRsp = 15,
    EWSCmdC2S_RegisterGroupReq = 16,
    EWSCmdS2C_RegisterGroupRsp = 17,
    EWSCmdC2S_UnRegisterGroupReq = 18,
    EWSCmdS2C_UnRegisterGroupRsp = 19,
    EWSCmdC2S_HeartBeatReq = 20,
    EWSCmdS2C_HeartBeatRsp = 21,
    EWSCmdS2C_MsgPushReq_V2 = 22,
    EWSCmdC2S_WSHistoryMsgReq = 25,
    EWSCmdS2C_WSHistoryMsgRsp = 26,
    EWSCmdS2C_EnterP2P = 27,
    EWSCmdS2C_EnterP2PAck = 28,
    EWSCmdS2C_ExitP2P = 29,
    EWSCmdS2C_ExitP2PAck = 30,
    EWSCmdC2S_SyncGroupReq = 31,
    EWSCmdS2C_SyncGroupRsp = 32,
    EWSCmdC2S_UpdateUserInfoReq = 33,
    EWSCmdS2C_UpdateUserInfoRsp = 34,
    EWSCmdC2S_MsgAckReq = 35,
    EWSCmdS2C_MsgAckRsp = 36,
    EWSCmdC2S_CloudGameReq = 37,
    EWSCmdS2C_CloudGamePush = 38,
    EWSCmdS2C_CloudGameRsp = 39,
    EWSCmdS2C_RpcReq = 40,
    EWSCmdC2S_RpcRsp = 41,
    EWSCmdS2C_RpcRspRsp = 42,
    EWSCmdC2S_GetStunPortReq = 101,
    EWSCmdS2C_GetStunPortRsp = 102,
    EWSCmdC2S_WebRTCOfferReq = 103,
    EWSCmdS2C_WebRTCOfferRsp = 104,
    EWSCmdC2S_SignalUpgradeReq = 105,
    EWSCmdS2C_SignalUpgradeRsp = 106
}

internal enum EDecorationViewType
{
    kDecorationViewTypeCustomized = 0,
    kDecorationViewTypeText = 1,
    kDecorationViewTypeIcon = 2,
    kDecorationViewTypeSuperWord = 4,
}

internal enum EDecorationAppType
{
    kDecorationAppTypeCommon = 100,
    kDecorationAppTypeContentBubble = 5000,
    kDecorationAppTypeContentBubbleNew = 5001,
    kDecorationAppTypeEffectsMessenger = 5002,
    kDecorationAppTypeMsgInterConnect = 5010,
    kDecorationAppTypeMsgLocation = 5011,
    kDecorationAppTypeChannel = 10000,
    kDecorationAppTypeGuildAdmin = 10090,
    kDecorationAppTypeAdmin = 10100,
    kDecorationAppTypeDaiyanClub = 10150,
    kDecorationAppTypeNoble = 10200,
    KDecorationAppTypeGuildVip = 10210,
    kDecorationAppTypeGuard = 10300,
    kDecorationAppTypeDiamondUser_V2 = 10310,
    kDecorationAppTypeTeamMedalV2 = 10350,
    kDecorationAppTypeTrialFans = 10399,
    kDecorationAppTypeFans = 10400,
    kDecorationAppTypeWatchTogetherVip = 10425,
    kDecorationAppTypeTeamMedal = 10450,
    kDecorationAppTypeVIP = 10500,
    kDecorationAppTypeUserProfile = 10560,
    kDecorationAppTyperPurpleDiamond = 10600,
    kDecorationAppTypeStamp = 10700,
    KDecorationAppTypeNobleEmoticon = 10800,
    KDecorationAppTypePresenter = 10900,
    KDecorationAppTypeFirstRecharge = 11000,
    kDecorationAppTypeCheckRoom = 11100,
    kDecorationAppTypeTWatch = 11101,
    kDecorationAppTypeEasterEgg = 11102,
    kDecorationAppTypeRepeatMessengeFilter = 11103,
    kDecorationAppTypeEasterEggCounter = 11104,
    kDecorationAppTypeACOrderIntimacy = 12001,
    kDecorationAppTypeSuperWord = 13000,
    kDecorationAppTypeDiamondUser = 14000,
    kDecorationAppTypeRedBag = 15000,
    kDecorationAppTypeUsrAvatarDeco = 100009,
    kDecorationAppTypeUsrBeautyId = 100100,
}

internal enum EClientTemplateType
{
    TPL_PC = 64,
    TPL_WEB = 32,
    TPL_JIEDAI = 16,
    TPL_TEXAS = 8,
    TPL_MATCH = 4,
    TPL_HUYAAPP = 2,
    TPL_MIRROR = 1,
}
